# Netlify Configuration for Marketing Basics Simulator

[build]
  # Build command
  command = "npm run build"
  
  # Directory with the production build files
  publish = "dist"
  
  # Environment variables (set these in Netlify dashboard)
  # VITE_GROQ_API_KEY = "your_groq_api_key_here"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Fix Netlify's automatic boolean setting
  SECRETS_SCAN_ENABLED = "false"

# Environment variables are properly configured in Netlify dashboard

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { Cache-Control = "no-cache, no-store, must-revalidate" }

# NUCLEAR REDIRECTS - Force new version
[[redirects]]
  from = "/#/sales-challenge"
  to = "/#/promotion-campaign?nuclear=true&v=4.0.0"
  status = 301
  force = true

[[redirects]]
  from = "/#/dashboard"
  to = "/#/promotion-campaign?nuclear=true&v=4.0.0"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/#/promotion-campaign?nuclear=true&v=4.0.0"
  status = 301
  force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # AGGRESSIVE NO-CACHE - Force fresh content
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "0"
    ETag = "0"

# Fix MIME types for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Fix MIME types for CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Fix MIME types for assets - JavaScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Fix MIME types for assets - CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Override Netlify's default behavior for all assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file - force fresh content
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.js"
  [headers.values]
    # JavaScript files with versioned names can be cached
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # CSS files with versioned names can be cached
    Cache-Control = "public, max-age=31536000, immutable"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Optimize images
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Functions directory (if needed in future)
[functions]
  directory = "netlify/functions"

